version: "3.7"

services:
  c:
    platform: linux/amd64
    image: 'eduinlight/c-cpp-local-dev'
    build:
      context: .
      target: dev
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
